### ISSUE TITLE
SyntaxError right after launching the app

### ISSUE THREAD

**Issue by EduardoFromTheFuture** [yugasun/vue-template#2]
When launching the app on a firefox browser, I get the following error on the browser console:

SyntaxError: import declarations may only appear at top level of a module

On the file worker.js:1

`import '/node_modules/.pnpm/vite@2.9.8_sass@1.51.0/node_modules/vite/dist/client/env.mjs'`

**Comment by yugasun** [comment]
> When launching the app on a firefox browser, I get the following error on the browser console:
> 
> SyntaxError: import declarations may only appear at top level of a module
> 
> On the file worker.js:1
> 
> `import '/node_modules/.pnpm/vite@2.9.8_sass@1.51.0/node_modules/vite/dist/client/env.mjs'`

@PinkFromTheFuture Because `Module Worker` is not supported in Firefox currently.
https://developer.mozilla.org/en-US/docs/Web/API/Worker#browser_compatibility
